/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkoutRouteImport } from './routes/workout'
import { Route as VoiceRouteImport } from './routes/voice'
import { Route as TodayRouteImport } from './routes/today'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as RestoreRouteImport } from './routes/restore'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HealthRouteImport } from './routes/health'
import { Route as DiaryRouteImport } from './routes/diary'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as BarcodeRouteImport } from './routes/barcode'
import { Route as AddFoodRouteImport } from './routes/add-food'
import { Route as IndexRouteImport } from './routes/index'

const WorkoutRoute = WorkoutRouteImport.update({
  id: '/workout',
  path: '/workout',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const RestoreRoute = RestoreRouteImport.update({
  id: '/restore',
  path: '/restore',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DiaryRoute = DiaryRouteImport.update({
  id: '/diary',
  path: '/diary',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const BarcodeRoute = BarcodeRouteImport.update({
  id: '/barcode',
  path: '/barcode',
  getParentRoute: () => rootRouteImport,
} as any)
const AddFoodRoute = AddFoodRouteImport.update({
  id: '/add-food',
  path: '/add-food',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-food': typeof AddFoodRoute
  '/barcode': typeof BarcodeRoute
  '/coach': typeof CoachRoute
  '/diary': typeof DiaryRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/platform': typeof PlatformRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/progress': typeof ProgressRoute
  '/restore': typeof RestoreRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/subscription': typeof SubscriptionRoute
  '/terms': typeof TermsRoute
  '/today': typeof TodayRoute
  '/voice': typeof VoiceRoute
  '/workout': typeof WorkoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-food': typeof AddFoodRoute
  '/barcode': typeof BarcodeRoute
  '/coach': typeof CoachRoute
  '/diary': typeof DiaryRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/platform': typeof PlatformRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/progress': typeof ProgressRoute
  '/restore': typeof RestoreRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/subscription': typeof SubscriptionRoute
  '/terms': typeof TermsRoute
  '/today': typeof TodayRoute
  '/voice': typeof VoiceRoute
  '/workout': typeof WorkoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-food': typeof AddFoodRoute
  '/barcode': typeof BarcodeRoute
  '/coach': typeof CoachRoute
  '/diary': typeof DiaryRoute
  '/health': typeof HealthRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/platform': typeof PlatformRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/progress': typeof ProgressRoute
  '/restore': typeof RestoreRoute
  '/scan': typeof ScanRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/subscription': typeof SubscriptionRoute
  '/terms': typeof TermsRoute
  '/today': typeof TodayRoute
  '/voice': typeof VoiceRoute
  '/workout': typeof WorkoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-food'
    | '/barcode'
    | '/coach'
    | '/diary'
    | '/health'
    | '/login'
    | '/onboarding'
    | '/platform'
    | '/privacy'
    | '/privacy-policy'
    | '/progress'
    | '/restore'
    | '/scan'
    | '/settings'
    | '/signup'
    | '/subscription'
    | '/terms'
    | '/today'
    | '/voice'
    | '/workout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-food'
    | '/barcode'
    | '/coach'
    | '/diary'
    | '/health'
    | '/login'
    | '/onboarding'
    | '/platform'
    | '/privacy'
    | '/privacy-policy'
    | '/progress'
    | '/restore'
    | '/scan'
    | '/settings'
    | '/signup'
    | '/subscription'
    | '/terms'
    | '/today'
    | '/voice'
    | '/workout'
  id:
    | '__root__'
    | '/'
    | '/add-food'
    | '/barcode'
    | '/coach'
    | '/diary'
    | '/health'
    | '/login'
    | '/onboarding'
    | '/platform'
    | '/privacy'
    | '/privacy-policy'
    | '/progress'
    | '/restore'
    | '/scan'
    | '/settings'
    | '/signup'
    | '/subscription'
    | '/terms'
    | '/today'
    | '/voice'
    | '/workout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddFoodRoute: typeof AddFoodRoute
  BarcodeRoute: typeof BarcodeRoute
  CoachRoute: typeof CoachRoute
  DiaryRoute: typeof DiaryRoute
  HealthRoute: typeof HealthRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PlatformRoute: typeof PlatformRoute
  PrivacyRoute: typeof PrivacyRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProgressRoute: typeof ProgressRoute
  RestoreRoute: typeof RestoreRoute
  ScanRoute: typeof ScanRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SubscriptionRoute: typeof SubscriptionRoute
  TermsRoute: typeof TermsRoute
  TodayRoute: typeof TodayRoute
  VoiceRoute: typeof VoiceRoute
  WorkoutRoute: typeof WorkoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workout': {
      id: '/workout'
      path: '/workout'
      fullPath: '/workout'
      preLoaderRoute: typeof WorkoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restore': {
      id: '/restore'
      path: '/restore'
      fullPath: '/restore'
      preLoaderRoute: typeof RestoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diary': {
      id: '/diary'
      path: '/diary'
      fullPath: '/diary'
      preLoaderRoute: typeof DiaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/barcode': {
      id: '/barcode'
      path: '/barcode'
      fullPath: '/barcode'
      preLoaderRoute: typeof BarcodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-food': {
      id: '/add-food'
      path: '/add-food'
      fullPath: '/add-food'
      preLoaderRoute: typeof AddFoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddFoodRoute: AddFoodRoute,
  BarcodeRoute: BarcodeRoute,
  CoachRoute: CoachRoute,
  DiaryRoute: DiaryRoute,
  HealthRoute: HealthRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PlatformRoute: PlatformRoute,
  PrivacyRoute: PrivacyRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProgressRoute: ProgressRoute,
  RestoreRoute: RestoreRoute,
  ScanRoute: ScanRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SubscriptionRoute: SubscriptionRoute,
  TermsRoute: TermsRoute,
  TodayRoute: TodayRoute,
  VoiceRoute: VoiceRoute,
  WorkoutRoute: WorkoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
