// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Public Supabase project URL and anon key. These are SAFE to commit:
// - URL is the project endpoint (public).
// - The anon key is the publishable key designed to be shipped to browsers;
//   Row Level Security on the Supabase side enforces per-user access.
// We keep env-var overrides so local dev / staging can point at a different project.
const FALLBACK_SUPABASE_URL = 'https://mkwdfbffcboqzyspuhmt.supabase.co';
const FALLBACK_SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1rd2RmYmZmY2JvcXp5c3B1aG10Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk5MTYwODAsImV4cCI6MjA5NTQ5MjA4MH0.wFePjCha---Sd8Pc_pcLx1itvBcOYkk2fx100P7NXb8';

function createSupabaseClient() {
  const SUPABASE_URL =
    import.meta.env.VITE_SUPABASE_URL ||
    (typeof process !== 'undefined' ? process.env.SUPABASE_URL : undefined) ||
    FALLBACK_SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
    (typeof process !== 'undefined' ? process.env.SUPABASE_PUBLISHABLE_KEY : undefined) ||
    FALLBACK_SUPABASE_PUBLISHABLE_KEY;

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
      flowType: 'pkce',
      // We complete the OAuth/email PKCE code exchange explicitly in
      // src/hooks/use-auth.ts so we get deterministic success/error handling
      // instead of racing supabase-js's automatic URL detection.
      detectSessionInUrl: false,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

